import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RQProvider from "@/components/providers/RQProvider";
import { Toaster } from "sonner";
import DialogLayout from "@/components/DialogLayout";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import ProgressLoaderProvider from "@/components/providers/ProgressLoaderProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <RQProvider>
            <ProgressLoaderProvider>
              {children}
              <Toaster position="top-right" />
              <DialogLayout />
            </ProgressLoaderProvider>
          </RQProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
